---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: centos-6.9
- name: centos-7.3
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: ubuntu-16.04
#- name: debian-6.0.10
- name: debian-7.11
- name: debian-8.6

suites:
- name: clients-5.5
  run_list:
    - recipe[mariadb::client]
  attributes:
    mariadb:
      version: 5.5
  excludes:
    - ubuntu-16.04
- name: servers-5.5
  run_list:
    - recipe[mariadb::server]
  attributes:
    mariadb:
      version: 5.5
      server_debian_password: 'ilovestrongpasswords'
      server_root_password:   'ilovestrongpasswords'
      server_repl_password:   'ilovestrongpasswords'
  excludes:
    - ubuntu-16.04
- name: clients-10.0
  run_list:
    - recipe[mariadb::client]
  attributes:
    mariadb:
      version: 10.0
- name: servers-10.0
  run_list:
    - recipe[mariadb::server]
  attributes:
    mariadb:
      version: 10.0
      server_debian_password: 'ilovestrongpasswords'
      server_root_password:   'ilovestrongpasswords'
      server_repl_password:   'ilovestrongpasswords'
